### ISSUE TITLE
卸载不了

### ISSUE THREAD

**Issue by YUNGUPAIN** [lonecloud/QQMessageInvoke#4]
卸载的代码不能使用，QQ一直处于加载时间过长的问题当中。

**Comment by lonecloud** [comment]
@YUNGUPAIN 
>该问题为你的QQ由于在启动的时候需要全面加载你的信息文件以及你的聊天文件

解决这个问题我也帮你一段脚本，请注意**如下脚本会删除您的个人聊天记录以及账号信息**
1. 打开终端，复制如下代码
```shell
# 以下脚本是删除相关的QQ历史数据
rm -rf ~/Library/Application Support/QQ
rm -ef ~/Library/Containers/com.tencent.qq/Data
```
2. 重新启动该QQ即可解决该问题
